# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79e867ffec0abddb149bf2d75744fe7dfed71a81bb9f4a54d456994f44f05ce88d6095d35e829dfde7dc46810e8ccff6edf460e291cbff9e8a1d9243e9510f00
  twitter_provider_key: <%= ENV["TWITTER_PROVIDER_KEY"] %>
  twitter_provider_secret: <%= ENV["TWITTER_PROVIDER_SECRET"] %>

test:
  secret_key_base: 97c7ce3e9d480bcda2267b1bd2f0cf8a32f57eb748ea88e768d62329aeebdad3363e5f389691286fffea1dad48d2eb10e7e41086496a08936a7635d29b1ba276

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twitter_provider_key: <%= ENV["TWITTER_PROVIDER_KEY"] %>
  twitter_provider_secret: <%= ENV["TWITTER_PROVIDER_SECRET"] %>

